---
name: renku-test
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - matplotlib
      - pandas
      - ipywidgets
      - pytest
      - scikit-learn
      - bokeh
